### ISSUE TITLE
SVG import error

### ISSUE THREAD

**Issue by ndeboar** [Aeoll/Aelib#12]
Hey man, love AE. 

SVG import worked in in Houdini 18, just moved to 19 and not sure if this is Python 3 related:
`No module named 'tinycss'`

Cheers,

Nick

**Comment by Aeoll** [comment]
Hi Nick,

Could you try the latest master branch and a py3.7 build of 19 or 19.5?

tinycss is included in /python3.7libs so it should pick up (it's working for me anyway!)

**Comment by ndeboar** [comment]
Thanks man, ill check it out!

Nick Deboar
------------------------------
www.nickdeboar.com
m +61 435887248
