### ISSUE TITLE
SVG import not support short HEX like #000

### ISSUE THREAD

**Issue by woohahahaaa** [Aeoll/Aelib#21]
"When I export an SVG from Adobe Illustrator with strokes set to the color #000000, Illustrator shortens the color code to #000. However, when I try to import the SVG, this results in an error."

**Comment by Aeoll** [comment]
This should be fixed in the latest commit

**Comment by woohahahaaa** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
