### ISSUE TITLE
Attribute adjust orient 

### ISSUE THREAD

**Issue by antoniopepe82** [Aeoll/Aelib#24]
i upgraded to your last version of AELIB

with a project i already have i get this error and the problem was that the orientation is not the same as the old version. 

Warning 
"/obj/RND6_SMALL/attribadjustorient1/EulerRotationFilter_TODO" using incomplete asset definition (full definition not found). 

![hindie_zux0AuJbD7](https://github.com/user-attachments/assets/b97539a9-a7c6-4a6a-98dd-5790dfa23e4d)

**Comment by Aeoll** [comment]
I've removed the missing HDA which wasn't being used.

Apologies if the orientation behaviour has changed. I'm not sure when this happened - it's likely the old behaviour was incorrect in some way and a fix went through.

**Comment by antoniopepe82** [comment]
Thanks 🤟. No problem I will tryI'll try it when I get back from vacation, Thanks
