### ISSUE TITLE
Curve Biased Resample not working correctly

### ISSUE THREAD

**Issue by charlesnyiha** [Aeoll/Aelib#4]
Hello,

Since the new Aelibs cleanup, the Curve Biased Resample node seems to be broken. I've attached some images where I attempt to resample a line and it doesn't work as expected.

![1](https://user-images.githubusercontent.com/54474398/101986288-44b2cd00-3c9e-11eb-8339-f75e8087927f.jpg)
![2](https://user-images.githubusercontent.com/54474398/101986291-49778100-3c9e-11eb-89b8-44c1a570cbb1.jpg)
![3](https://user-images.githubusercontent.com/54474398/101986294-4d0b0800-3c9e-11eb-810c-513abf45cb7c.jpg)

Thank you!

**Comment by Aeoll** [comment]
Thanks for the report - definitely something going wrong here, will take a look.

In the meantime SideFX Labs has a 'Progressive Resample' SOP which has similar behaviour.
