### ISSUE TITLE
Syntax Error in Chaotic Attractor

### ISSUE THREAD

**Issue by ChrisP3D** [Aeoll/Aelib#6]
'/obj/geo1/ChaoticAttractor1/INTEGRATOR/d/s/thomas'

When choosing the thomas attractor it errors out immediately.
Inside of the sop solver, the thomas wrangle, line 4 just needs a semi colon after the dt scaling channel line.

In the TSUCS_1 wrangle, it generates points, but does not change their position. It needs an offset to start attracting. I'm sure people could figure it out on their own, but maybe a hidden toggle parameter that only shows when {attractor == 'TSUCS_1'} could help jump start the process. I thought this might add fluidity to the tool, because all of the other algorithms work without needing input.

This is my first bug report ever. Hope it helps and thank you for creating these amazing tools!

**Comment by Aeoll** [comment]
Hi,

Thanks for the report - I've made these changes to the dev branch. This SOP is quite old and could definitely be more user friendly. I don't use it much though so I probably won't have the time/energy to rebuild it!

**Comment by ChrisP3D** [comment]
Cool. They are new to me. It was a fun exercise to try to solve the problem
for me. Thanks again for sharing this project.
