### ISSUE TITLE
 ae_SVG export with camera?

### ISSUE THREAD

**Issue by paul-ferragut** [Aeoll/Aelib#8]
Thank you for doing Aelib!
I am exporting wireframes of 3D models to 2D with ae_SVG_export.
How to use the input 'Optional Bounding Box To Define SVG View'?
Is it possible to export from a camera view?
Is it possible to export with view-frustrum and occlusion culling?
Thank you

**Comment by Aeoll** [comment]
Hi Paul,

Sounds like perhaps you have a pen plotter?

The bbox input can be used to force the svg into a given 'box' - aligning your geo properly and adding margins etc.

As for your other 2 queries:
- camera project ql is a good hda for cam projections into 2D (qlib)
- for frustum culling aelib has a camera cull hda 
- I do have an occlusion (hidden line removal) hda but it's private at the moment at it's a bit messy!

Cheers
