### ISSUE TITLE
Collect Files Script - Error Message is quite broad

### ISSUE THREAD

**Issue by labmeta** [Aeoll/Aelib#9]
Hey Nick,

Great collection of scripts! I was just having a go with the collect hip script.

I find it works in some cases, but often falls over complaining of a list of potential problems that might include locked nodes, individual permissions, disk permissions etc. Quite vague in terms of tracking the issue down when in a large scene.

Is there a more verbose log produced anywhere to help find out the specific item causing the problem?

Thanks,

Paul

**Comment by Aeoll** [comment]
Hi Paul,

Yes unfortunately I ran into a lot of edge cases when I wrote the script a
few years ago so it's never really felt complete and fully usable. Larger
scenes are more likely to fail as you've found.

Improving it has been on my list for a while but the time is never there.
Sorry that I can't give you a better answer!

Thanks
Nick
